name: CI for SCCstore

on:
  push:
    # branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Project 
      uses: actions/checkout@v4

    # for docker build see https://docs.docker.com/ci-cd/github-actions/
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push - ansible-pg
      id: docker_build_ansible-pg
      uses: docker/build-push-action@v6
      with:
        context: ./ansible-pg/
        file: ./ansible-pg/Containerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dpiol-ansible:latest,${{ secrets.DOCKER_HUB_USERNAME }}/dpiol-ansible:${{ github.ref_name }} 

    - name: Image digest - ansible-pg
      run: echo ${{ steps.docker_build_ansible-pg.outputs.digest }}

